// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function handleClick(_event) {
  console.log("clicked!");
  return /* () */0;
}

var maybeString2 = "foo";

if (maybeString2 !== undefined) {
  console.log("string is here: " + maybeString2);
} else {
  console.log("no string");
}

var foo = (console.log("no string"), /* () */0);

var bar = Belt_Option.getExn(Belt_Option.map("foofoo", (function (a) {
            return a;
          })));

function Component1(Props) {
  var message = Props.message;
  console.log(bar);
  return React.createElement("div", {
              onClick: handleClick
            }, message);
}

var make = Component1;

exports.handleClick = handleClick;
exports.foo = foo;
exports.bar = bar;
exports.make = make;
/*  Not a pure module */
