// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Main$ReactHooksTemplate = require("./Main.bs.js");

function filterFunc(x) {
  return Caml_option.some(x);
}

var data = /* record */[
  /* name : record */[
    /* firstName */"Bijan",
    /* middleName */"Alain",
    /* lastName */"Chokoufe Nejad"
  ],
  /* headline */"Scala Developer at enfore - PhD Physics",
  /* location */"Hamburg",
  /* summary : record */[/* content */"After my PhD in theoretical physics, I followed my passion for functional programming and clean code. I like to find simple solutions to complex problems.\n    Also: I'm a Prachtbursche! ;)\n    "],
  /* socials : [] */0,
  /* work : :: */[
    /* record */[
      /* startDate : record */[/* repr */"September 2009"],
      /* endDate : record */[/* repr */"Present"],
      /* company */"enfore",
      /* website */"???",
      /* position */"Software Engineer",
      /* summary */"doing stuff",
      /* highlights : :: */[
        "this",
        /* :: */[
          "that",
          /* :: */[
            "more",
            /* [] */0
          ]
        ]
      ]
    ],
    /* [] */0
  ],
  /* education : [] */0,
  /* publications : [] */0,
  /* skills : [] */0,
  /* languages : [] */0
];

function parseDataFromJSON(param) {
  return data;
}

function render(param) {
  return ReactDOMRe.renderToElementWithId(React.createElement(Main$ReactHooksTemplate.make, {
                  data: data,
                  filterFunc: filterFunc
                }), "main");
}

render(/* () */0);

var chosenTheme = /* Lean */0;

exports.filterFunc = filterFunc;
exports.data = data;
exports.parseDataFromJSON = parseDataFromJSON;
exports.chosenTheme = chosenTheme;
exports.render = render;
/*  Not a pure module */
