// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function Main$Summary(Props) {
  var summary = Props.summary;
  return React.createElement("p", {
              className: "lead mb-5"
            }, summary[/* content */0]);
}

var Summary = /* module */[/* make */Main$Summary];

function Main$Banner(Props) {
  var name = Props.name;
  var headline = Props.headline;
  var $$location = Props.location;
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "mb-0"
                }, name[/* firstName */0] + (" " + name[/* middleName */1]), React.createElement("span", {
                      className: "text-primary"
                    }, " " + name[/* lastName */2])), React.createElement("div", {
                  className: "subheading mb-5"
                }, headline + (" - " + ($$location + " - ")), React.createElement("a", {
                      href: "mailto:name@email.com"
                    }, "name@email.com")));
}

var Banner = /* module */[/* make */Main$Banner];

function Main$Work(Props) {
  var work = Props.work;
  return React.createElement("div", undefined, React.createElement("h2", {
                  className: "mb-5"
                }, "Experience"), React.createElement("div", {
                  className: "resume-item d-flex flex-column flex-md-row justify-content-between mb-5"
                }, React.createElement("div", {
                      className: "resume-content"
                    }, React.createElement("h3", {
                          className: "mb-0"
                        }, "Software Engineer"), React.createElement("div", {
                          className: "subheading mb-3"
                        }, "enfore"), React.createElement("p", undefined, "doing stuff")), React.createElement("div", {
                      className: "resume-date text-md-right"
                    }, React.createElement("span", {
                          className: "text-primary"
                        }, "September 2009 - Present"))), String(work));
}

var Work = /* module */[/* make */Main$Work];

function Main$Socials(Props) {
  var socials = Props.socials;
  console.log(String(socials));
  return React.createElement("div", {
              className: "social-icons"
            }, React.createElement("a", {
                  href: "#"
                }, React.createElement("i", {
                      className: "fab fa-linkedin-in"
                    })), React.createElement("a", {
                  href: "#"
                }, React.createElement("i", {
                      className: "fab fa-xing"
                    })), React.createElement("a", {
                  href: "#"
                }, React.createElement("i", {
                      className: "fab fa-github"
                    })), React.createElement("a", {
                  href: "#"
                }, React.createElement("i", {
                      className: "fab fa-gitter"
                    })), React.createElement("a", {
                  href: "#"
                }, React.createElement("i", {
                      className: "fab fa-twitter"
                    })));
}

var Socials = /* module */[/* make */Main$Socials];

function Main$Education(Props) {
  var educations = Props.educations;
  return React.createElement("div", undefined, String(educations));
}

var Education = /* module */[/* make */Main$Education];

function Main$ListItem(Props) {
  var displayString = Props.displayString;
  return React.createElement("li", {
              className: "nav-item"
            }, React.createElement("a", {
                  className: "nav-link js-scroll-trigger active",
                  href: "#" + $$String.lowercase(displayString)
                }, displayString));
}

var ListItem = /* module */[/* make */Main$ListItem];

function Main$Navigation(Props) {
  var data = Props.data;
  return React.createElement("nav", {
              className: "navbar navbar-expand-lg navbar-dark bg-primary fixed-top",
              id: "sideNav"
            }, React.createElement("a", {
                  className: "navbar-brand js-scroll-trigger",
                  href: "#page-top"
                }, React.createElement("span", {
                      className: "d-block d-lg-none"
                    }, data[/* name */0][/* lastName */2]), React.createElement("span", {
                      className: "d-none d-lg-block"
                    }, React.createElement("img", {
                          className: "img-fluid img-profile rounded-circle mx-auto mb-2",
                          alt: "",
                          src: "../profile.jpg"
                        }))), React.createElement("button", {
                  "aria-label": "Toggle navigation",
                  "aria-controls": "navbarSupportedContent",
                  className: "navbar-toggler",
                  type: "button"
                }, React.createElement("span", {
                      className: "navbar-toggler-icon"
                    })), React.createElement("div", {
                  className: "collapse navbar-collapse",
                  id: "navbarSupportedContent"
                }, React.createElement("ul", {
                      className: "navbar-nav"
                    }, React.createElement(Main$ListItem, {
                          displayString: "About"
                        }), React.createElement(Main$ListItem, {
                          displayString: "Experience"
                        }), React.createElement(Main$ListItem, {
                          displayString: "Education"
                        }), React.createElement(Main$ListItem, {
                          displayString: "Skills"
                        }), React.createElement(Main$ListItem, {
                          displayString: "Interests"
                        }), React.createElement(Main$ListItem, {
                          displayString: "Awards"
                        }))));
}

var Navigation = /* module */[/* make */Main$Navigation];

function Main(Props) {
  var data = Props.data;
  var filterFunc = Props.filterFunc;
  Belt_Option.map(Belt_Option.map(Curry._1(filterFunc, data), (function (x) {
              return x[/* headline */1];
            })), (function (prim) {
          console.log(prim);
          return /* () */0;
        }));
  return React.createElement("div", undefined, React.createElement(Main$Navigation, {
                  data: data
                }), React.createElement("section", {
                  className: "resume-section p-3 p-lg-5 d-flex align-items-center",
                  id: "about"
                }, React.createElement("div", {
                      className: "w-100"
                    }, React.createElement(Main$Banner, {
                          name: data[/* name */0],
                          headline: data[/* headline */1],
                          location: data[/* location */2]
                        }), React.createElement(Main$Summary, {
                          summary: data[/* summary */3]
                        }), React.createElement(Main$Socials, {
                          socials: data[/* socials */4]
                        }))), React.createElement("hr", {
                  className: "m-0"
                }), React.createElement("section", {
                  className: "resume-section p-3 p-lg-5 d-flex align-items-center",
                  id: "experience"
                }, React.createElement("div", {
                      className: "w-100"
                    }, React.createElement(Main$Work, {
                          work: data[/* work */5]
                        }))), React.createElement("hr", {
                  className: "m-0"
                }), React.createElement("section", {
                  className: "resume-section p-3 p-lg-5 d-flex align-items-center",
                  id: "education"
                }, React.createElement("div", {
                      className: "w-100"
                    }, React.createElement(Main$Education, {
                          educations: data[/* education */6]
                        }))));
}

var make = Main;

exports.Summary = Summary;
exports.Banner = Banner;
exports.Work = Work;
exports.Socials = Socials;
exports.Education = Education;
exports.ListItem = ListItem;
exports.Navigation = Navigation;
exports.make = make;
/* react Not a pure module */
